version: "3.7"
networks:
  stockforecastnetwork: 
    driver: bridge
services:
  web:
    user: root
    container_name: wscontainer
    networks:
      - stockforecastnetwork
    build:
      context: .
    volumes:
      - .:/webserver
      - video_data:/webserver/videos
      - static_data:/vol/web/static
    environment:
      - DEBUG=0
    depends_on:
      - db
  db:
    container_name: dbcontainer
    networks:
      - stockforecastnetwork

    image: timescale/timescaledb:latest-pg14
    ports:
      - 6432:5432
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  proxy:
    user: root
    container_name: proxycontainer
    networks:
      - stockforecastnetwork
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
      - "8001:8001"
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy:/etc/nginx/
      - static_data:/vol/static
      - ./media:/vol/media
      - video_data:/vol/videos
      - ./frontend/build:/vol/react
    depends_on:
      - web

volumes:
  db_vol: 
  static_data:
  video_data:
  acme_ecc:

